### ISSUE TITLE
Change user agent

### ISSUE THREAD

**Issue by mlhess** [lauriii/drupalcores#121]
Please change the user agent that this pulls information as (right now it seems to be a generic ruby user agent).  The infra team was looking at traffic and almost blocked this as it appears to be running from a shared ip address.

Feel free to contact me directly if you have more questions.

**Comment by lauriii** [comment]
@mlhess that could have been someone running the app locally. The app is hosted on 54.72.65.1 and has a dedicated IP address.

**Comment by mlhess** [comment]
Sounds good.

**Comment by jcnventura** [comment]
Probably me while testing. In any case, I've made a patch to add a user agent to the request.
