### ISSUE TITLE
Reverted commits should remove 2 commit mentions instead of one

### ISSUE THREAD

**Issue by pcambra** [lauriii/drupalcores#38]
The flow is normally:

Bunch of work
Commit
https://www.youtube.com/watch?v=1EBfxjSFAxQ
Revert
Bunch of work 
Commit

When it finally goes in, it should be counted as 1 and now I think it's counted as 2.

**Comment by lewisnyman** [comment]
I'm not sure if I understand this code but it looks like:

```
%x[#{git_command}].split("\n").each do |c|
  if c.index('Revert') == 0 then
    reverts.push(c.scan(/#([0-9]+)/))
  else
    commits.push(c)
  end
end
```

If it finds a reverted commit then it never counts that commit, so later it removes the reverted commit from the count.

**Comment by pcambra** [comment]
Finally was able to install and run it.

This is how a revert process normally looks like

```
git log --pretty=oneline | grep 1425330
e5fe68e2a0eb427e3cab8ea6f6d5e7643b1aba98 Issue #1425330 by swentel, grendzy, davereid, wojtha, c960657: Fixed Apply Aggregator and OpenID fixes from DRUPAL-SA-CORE-2012-001.
28b68ad75dc627ec278397bf3a1fe36628ffb6c0 Revert "Issue #1425330 by swentel, grendzy, davereid, wojtha, c960657: Fixed Apply Aggregator and OpenID fixes from DRUPAL-SA-CORE-2012-001."
c3fa160dca988c221d7a34c327fd8c81a4df2483 Issue #1425330 by swentel, grendzy, davereid, wojtha, c960657: Fixed Apply Aggregator and OpenID fixes from DRUPAL-SA-CORE-2012-001.
```

So when a revert process happens in a normal way - or at least with an issue number -, the commit is counted twice because only the revert is being removed from the count and what is expected is that both the Revert and the original commit should be "discounted".

Another thing that is happening is that we're taking into account commits without issue number, and those are mostly coming from merges from VDC and DBTNG, and there's no need to evaluate those because they don't have "by" or anything (another discussion would be if the git author of that commit should be added to the count).

PR's coming soon :)
