### ISSUE TITLE
Automated update of JSON?

### ISSUE THREAD

**Issue by joshuataylor** [lauriii/drupalcores#55]
Is there an automatically updated JSON file somewhere?

I've currently got mine building everytime core is updated, which is found here: https://raw.githubusercontent.com/joshuataylor/drupalcores-data/master/data.json

**Comment by lewisnyman** [comment]
Yeah, it should be updated whenever the `gulp` command is run

**Comment by lewisnyman** [comment]
http://www.drupalcores.com/data.json
