### ISSUE TITLE
Wunderkraut logo is missing

### ISSUE THREAD

**Issue by jcnventura** [lauriii/drupalcores#58]
Wunderkraut, #9 in the top 10 Drupalcores company is missing the logo. Please fix it.

**Comment by jcnventura** [comment]
Running the script from scratch solves the problem.

**Comment by lewisnyman** [comment]
Sounds like we don't have gulp companyinfo running on cron

On Tuesday, 12 May 2015, Joao Ventura <notifications@github.com> wrote:

> Closed #58 <https://github.com/lauriii/drupalcores/issues/58>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lauriii/drupalcores/issues/58#event-303093315>.
>


-- 
Lewis Nyman
+447753103690
lewisnyman.co.uk <http://www.lewisnyman.co.uk>
@lewisnyman <http://twitter.com/lewisnyman>
