### ISSUE TITLE
agaric doesn't link to Agaric's d.o page

### ISSUE THREAD

**Issue by mlncn** [lauriii/drupalcores#98]
Hi, sorry, i can't see a way to fix this in the code.  My best guess is it's in data/company_infos.yml or data/company_mappings.yml which are no longer in the repository.

On http://drupalcores.com/companies.html agaric is listed and the people/commits look like it is attributed correctly, but it does not link to https://www.drupal.org/agaric

Thanks for the support!  (Took a closer look here thanks to David (gnuget)'s shoutout in http://agaric.com/blogs/start-contributing-drupal )

**Comment by lauriii** [comment]
I will rebuild the company data and let's hope it fixes this!

**Comment by lauriii** [comment]
Agaric has now a logo and a link on the companies list

**Comment by mlncn** [comment]
Thank you!
